site_name: FiveOrbs Sire
copyright: © 2022 ebene fünf GmbH
nav:
  - index.md
theme:
    name: fiveorbs
repo_url: https://github.com/fiveorbsdev/sire
extra:
    project: Sire
plugins:
    - search
    - macros:
        module_name: docs/main
markdown_extensions:
  - admonition
